Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
// Seção de Declarações das variáveis 
 nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 nome <- "Marcos"
 escreva("Muito prazer ",nome)

Fimalgoritmo