Algoritmo "primeiro"
// Disciplina  : [Linguagem e Lógica de Programação]
// Descrição   : Primeiro Programa
// Autor(a)    : Marcos Willian de Souza
// Data atual  : 24/05/2022
Var
  msg: caractere
Inicio

   Escreval("Ola Mundo!")
   Escreva("Me livrei da Maldição!")
   Escreval("")
   // segunda parte
   msg <- "Ola Mundo!"
   Escreval("msg")
   Escreval(msg)
   Escreval("Mensagem ",msg)


Fimalgoritmo