Algoritmo "valores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Marcos Willian de Souza
// Data atual  : 25/05/2022
Var
// Seção de Declarações das variáveis 
   N1, N2, S: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Informe um Numero: ")
  leia(n1)
  escreva("Informe outro Numero: ")
  leia(n2)
  S <- n1 + n2
  escreva("A soma entre ", N1, " e ", n2," é igual a ", S)
  

Fimalgoritmo