Algoritmo "valores1"
// Disciplina  : [Linguagem e Lógica de Programação]
// Autor(a)    : Marcos Willian de Souza
// Data atual  : 25/05/2022
Var
// Seção de Declarações das variáveis 
   N1, N2: inteiro
   M: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Informe um Numero: ")
  leia(n1)
  escreva("Informe outro Numero: ")
  leia(n2)
  M <- (N1 + N2) / 2
  escreva("A média entre ", N1, " e ", N2," é igual a ", M)
  

Fimalgoritmo